name: indexer
description: Indexer for Bluesky data
version: 1.0.0
repository: https://github.com/skyfeed-dev/indexer

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  lib5: ^0.1.0
  surrealdb:
    git: https://github.com/redsolver/surrealdb_flutter.git
  cbor: ^5.1.2
  web_socket_channel: ^2.4.0
  crypto: ^3.0.3
  alfred: ^1.1.0+1
  atproto_core: ^0.2.9
  influxdb_client: ^2.8.0
  atproto: ^0.2.13
  pool: ^1.5.1
  thirds: ^0.2.0-alpha.1
  dotenv: ^4.1.0
  logger: ^1.3.0
  s5_msgpack: ^0.3.0
  
dependency_overrides: 
  http: 1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
